### ISSUE TITLE
Just for chatting

### ISSUE THREAD

**Issue by james-stevens** [james-stevens/powerdns-webui#18]
This "issue" is opened so people can leave comments and feedback without having to open an issue or whatever. 

I couldn't find a better way of doing this. If you know of one, please let me know.

**Comment by Szabka** [comment]
Hi, first i want to thank you 4 your excellent work.
I recommend only few tweaks.
- put default_ttl to gbl variable block
- fill login form server and with_https field value from gbl initially

BR
  Szabka

**Comment by james-stevens** [comment]
> * put default_ttl to gbl variable block

Not sure what you mean?

> * fill login form server and with_https field value from gbl initially

I will fill in "with https" from the user's URL - like the server name, ok?

**Comment by james-stevens** [comment]
-  gbl.default_ttl only set the default TTL at login, after that it will retain your choice
- with_https checkbox is taken from the protocol field of the start up URL

**Comment by Szabka** [comment]
Sorry, i used the v0.9 version of the webui so my comments are not relevant any more.
I'm very happy with the updates. I see it prefills the server with window.location it would be nice to copy the port too, i currently run the webserver on non standard port.

**Comment by james-stevens** [comment]
your comments were correct, at the time, I added your recommendations to the code yesterday.
The port fix is now merged to `master`, so just re-pull / re-clone

**Comment by GongT** [comment]
Perfact job!

Maybe add a "deploy to sub-directory" feature? *(eg. `admin.example.com/pdns`)*

Current it already working when I append "/pdns" in the "Server: " field.   
But with 2 issue:
1. I must change Server everytime
1. `pushState` And "Change server" hard coded "/"

**Comment by james-stevens** [comment]
> Perfect job!

WOW - thank you so much :)

I will give this some thought. Right now I can't think of a way to make using a subdirectory generic.

For now, you might find it easier to just change the code - this is the line you need to change..

```
https://github.com/james-stevens/powerdns-webui/blob/master/htdocs/index.html#L2442
```
```
if (f.server.value == "") f.server.value = window.location.host;
```

Just change the `f.server.value = ` to the value you want :)

You could also take out the `if (f.server.value == "") ` prefix, if you are sure you always want the same value. I know this will make upgrading more difficult, but it will make your life a lot easier.

Retaining the server name you previously entered could be a nice generic solution. It would require a cookie, but seems to me this might be the easiest option?

**Comment by james-stevens** [comment]
> Maybe add a "deploy to sub-directory" feature? (eg. admin.example.com/pdns)

If you clone the latest `master` branch (or just download `index.html` from the `master` branch)  the latest code will save your `server` & `with https` login options as a cookie for 30 days. If you think it should use a longer time, let me know. I have no objection.

It deliberately does **not** save the API-Key, but you should be able to do this using your browser, if you wish.

If the cookie has expired, it falls back to getting the server & https from the URL, as before.

I've also fixed a bug in editing `metadata` and improved the failure handling, esp at login

**Comment by GongT** [comment]
Most important thing is there are two `window.history.pushState(state,title,'/');` in "index.html"    
It will cause:
1. open `127.0.0.1/pdns`
2. type in Key and click `Load Zone List`
3. zone list shown and **browser url changed to `127.0.0.1`**
I can't refresh page now.

**Comment by james-stevens** [comment]
K - so basically it fails if `index.html` isn't served from `/`

No prob - I'll look at this on Monday.

> Most important thing is there are two `window.history.pushState(state,title,'/');` in "index.html"
> It will cause:
> 
> 1. open `127.0.0.1/pdns`
> 2. type in Key and click `Load Zone List`
> 3. zone list shown and **browser url changed to `127.0.0.1`**
> 
> I can't refresh page now.

K - so basically sounds like it fails if `index.html` isn't served from `/`

No prob - I'll look at this on Monday.

**Comment by james-stevens** [comment]
I think I nailed it this time, please reclone `master` , 
or redownload `index.html` from `master` and try again

**Comment by Filip98** [comment]
Just wanted to say hi, I've starred this project since it's relatively early days, I'm glad you're still dedicated to it

**Comment by rockenren** [comment]
Hello,
thanks for really good and simple tool for PDNS management!

Don't have any issues, but couple of questions:

1. does it fully compatible with PowerDNS 4.3.x branch (and schema)? I've tried it with latest release from 4.3.x branch, seems to work ok.
2. whats the point of API key input on login page? I mean, you set "Dev-Key" as API key for pdns, then you set it as password for pdns webserver, and finally you set static "Dev-Key" in nginx proxy header. I don't fully understand this part. Can you please explain it a little bit more?

**Comment by james-stevens** [comment]
Thanks for the +ve feeback - its always appreciated.

(1) is still a fair question - I still run 4.2.2, so I've not tested it above that, but I suspect they will continue to make the API backwards compatible. Its possible there are some new features I could add, if they have improved the API since then.

For me a key design goal was that its only requirement should be the standard PDNS/API - this means some of more sophisticated features you get with some of the DB based tools are simply not possible (e.g. fine access control), but the benefit in the simplicity, for an admin tool, is worth it IMHO.

(2) allowing people to input an API key allows you to connect directly to the PDNS/API and means you don't need the intermediate web server / proxy. Some people find this is enough security for their situation. It means, for example, that you can take this tool onto a customer site and fire it up without having to have the web server etc - you just keep a copy of the HTML file on your laptop and open it, then you can connect to any PDNS server that has the API set up. I've seen people say this is what they use it for.

**Comment by rockenren** [comment]
Is there any chances for a small QoL fix?

![изображение](https://user-images.githubusercontent.com/11333307/94535132-a1cfe280-025a-11eb-805f-5ff182ccd521.png)

**Comment by james-stevens** [comment]
> Is there any chances for a small QoL fix?
> 
> ![изображение](https://user-images.githubusercontent.com/11333307/94535132-a1cfe280-025a-11eb-805f-5ff182ccd521.png)

Clone / download `index.html` from the latest `master` branch and give that a go - should be better :)

 I use 1920x1080, so didn't notice

If that fixes things for you, let me know and I'll make it a new release

**Comment by rockenren** [comment]
> I use 1920x1080, so didn't notice

this screenshot was taken on 1920x1080 screen too.

I think I've found a source of bug: no horizontal scroll in firefox, but horizontal scroll in chrome still persist even after last fix.

**Comment by james-stevens** [comment]
> > I use 1920x1080, so didn't notice
> 
> this screenshot was taken on 1920x1080 screen too.
> 
> I think I've found a source of bug: no horizontal scroll in firefox, but horizontal scroll in chrome still persist even after last fix.

![Selection_2020-09-29_009](https://user-images.githubusercontent.com/30622954/94594533-757b8c80-0281-11eb-99c0-c0ce1fe83a92.png)
![Selection_2020-09-29_008](https://user-images.githubusercontent.com/30622954/94594547-790f1380-0281-11eb-9088-9edfd81f890d.png)

These are from Chrome - I made the window smaller to force the wrap

In your example, the text has spaces, so it can wrap - in your real use are there no spaces?

**Comment by james-stevens** [comment]
> > I use 1920x1080, so didn't notice
> 
> this screenshot was taken on 1920x1080 screen too.
> 
> I think I've found a source of bug: no horizontal scroll in firefox, but horizontal scroll in chrome still persist even after last fix.

OK - try again now

I'm guessing its cos you have no spaces in your TXT data?

**Comment by rockenren** [comment]
> OK - try again now

seems ok now. Thank you.

> I'm guessing its cos you have no spaces in your TXT data?

yes, it's long record (public key) without spaces as showed in example: https://en.wikipedia.org/wiki/DomainKeys_Identified_Mail#Verification

Thank you again, now it's ok in both Chrome and Firefox.

**Comment by james-stevens** [comment]
This `issue` was opened just to leave feedback, but now github has `discussions` I have enabled it on this project, so plase feel free to use that to leave any aimless comments etc

**Comment by james-stevens** [comment]
please use `discussions` from now on :)

**Comment by kgnfth** [comment]
ugliest web ui i have ever seen in my whole live

**Comment by james-stevens** [comment]
> ugliest web ui i have ever seen in my whole live

You forgot to include your patch for something better
