### ISSUE TITLE
Cannot login in Chrome

### ISSUE THREAD

**Issue by gen2brain** [james-stevens/powerdns-webui#32]
```
Console was cleared
(index):1 [DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) <input type=​"password" size=​"40" name=​"apikey" value>​

(index):2431 Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at loadCookies (https://mytest.com/:2431:30)
    at startUp (https://mytest.com/:2445:2)
    at onload (https://mytest.com/:2602:27)
loadCookies @ (index):2431
startUp @ (index):2445
onload @ (index):2602

(index):312 Uncaught TypeError: Cannot read property 'forEach' of undefined
    at callApi ((index):312)
    at zoneList ((index):2293)
    at initialLogin ((index):2507)
    at HTMLSpanElement.onclick ((index):2616)
callApi @ (index):312
zoneList @ (index):2293
initialLogin @ (index):2507
onclick @ (index):2616
```

Works in Firefox though.
Chrome Version 81.0.4044.92 (Official Build) beta (64-bit).

**Comment by james-stevens** [comment]
> Console was cleared

Yeah, I find it easier for debugging to clear the console each time I reload new code, there is a tick box in the console settings ("Preserve log") that can block it being cleared, if you prefer - or just remove line `187`

> (index):1

No problem - easy to add

> (index):2431

this is trying to decode a base64 encoded JSON object, stored as a cookie to pre-fill the server & https fields in the login. It shouldn't matter that it fails. I can easily wrap it in a `try...except` to stop an error getting flagged.

Why you would have the cookie set, but for it to **not** be valid base64, I couldn't guess. If you clear the cookie, this issue should resolve. I guess, if you serve this page from a location that already has existing cookies, it might cause this issue? If this is the case, those cookies should really be protected from other people being able to read them.

NOTE: this cookie is purely about prefilling the login inputs, to the values you used the previous time, so should not affect your ability to login

> (index):312

This is extremely stange. The `forEach` at line `312` is on `gbl.forms`, which is pretty much a constant, set on line `2469`, in the function `startUp()`, which is called in the `onLoad` event of the page, line `2602`. So `gbl.forms` should **never** be undefined.

> Chrome Version 81.0.4044.92 (Official Build) beta (64-bit).

I use `Version 81.0.4044.138 (Official Build) (64-bit)` and it works fine. I always use Chrome and have never seen anything like you describe. I'm a little concerned you are using a `beta`, especially a beta with a version number older than the one I am using??

**Comment by james-stevens** [comment]
Just merged an update to master to add improvements I described.

**Comment by gen2brain** [comment]
Ok, works now, thanks!
About the version, there is a choice of google-chrome and google-chrome-beta, and on my OS they cannot be updated automatically, I just didn't update it yet.
