### ISSUE TITLE
Zones loading

### ISSUE THREAD

**Issue by gen2brain** [james-stevens/powerdns-webui#33]
I have a pdns with about 200K domains configured. Loading all zones at the start makes the page load after about 4min and JSON is 50M. Also, there is no indication if it actually loads something and if I should wait for it to finish.
`1 request
48.13 MB / 48.13 MB transferred
Finish: 3.49 min`

Not sure how API works but some paging by default would be nice.

**Comment by james-stevens** [comment]
There is no paging facility in the PowerDNS rest/api, so you have to load the entire zone list. I didn't want to go down the road of producing a rival rest/api, as that opens a whole different can of worms.

Loading of the initial zone list is about the only load that does get a "Loading ⌛" message, becuase the message area isn't yet visible at that time. I will look into this. On my system its instant, so it didn't occur to me :)

Once loaded, the zone list should/would appear in the window. I've never tested it up to 200K zones, however I did test a zone with 10K RRs and that worked fine, but I am on a reasonably fast & low latency link to my PDNS.

Your 50Mb @ 4mins, I make 2Mb/s, where as I have 75Mb/s download at about 14ms latency

**Comment by james-stevens** [comment]
just merged an update to master so you now get a "Loading￼" on the login screen, when first loading the zone list & the mouse pointer should change to "progress" for all fetches.

**Comment by gen2brain** [comment]
Ok, thanks, I will see if I can do something with caching, maybe on Nginx level.

**Comment by gen2brain** [comment]
I tested API with query parameter `dnssec=false` and the difference is huge:
```
# time curl -k 'https://localhost/api/v1/servers/localhost/zones?dnssec=false' >/dev/null 2>&1

real	0m6.819s
user	0m0.766s
sys	0m0.086s

# time curl -k 'https://localhost/api/v1/servers/localhost/zones?dnssec=true' >/dev/null 2>&1

real	3m44.059s
user	0m0.999s
sys	0m0.107s
```

There is more info about this option here https://github.com/PowerDNS/pdns/pull/4628

**Comment by james-stevens** [comment]
nice find - although not the nicest solution :)

If you download `index.html` from the `dev` branch, I've added a `Fast Zone List` option on the login screen, which will also get saved into the cookies, to be remembered next time.

Let me know if this works for you.

I tried it on my system, and the zone list omitted the DNSSEC information it would have otherwise included, so looks like it worked for me.

**Comment by gen2brain** [comment]
Yes, works much better now, with fast zone list whole page is loaded and rendered after 26sec, that is tolerable and I can work with that. Also, a good motivation now to clean all dead domains from the database :).
Not sure though do you need an option at all, why not default to dnssec=false, but just for listing the zones.

**Comment by james-stevens** [comment]
I like to see which zones are signed and which have not been NOTIFIED, in the zone listing. When you have `dnssec=false` you lose that.

![Selection_2020-05-15_001](https://user-images.githubusercontent.com/30622954/82068799-65944f00-96ca-11ea-950a-cc57fe433718.png)

The lock shows DNSSEC signed zones, there would be an hourglass in the far-right column if there are unnotified changes. This only matters if you use RFC (not native) slaves, like bind etc.

I have distant remote slaves, so using RFC zone transfer is more reliable than trying to replicate a database over long distances.

**Comment by gen2brain** [comment]
OK, I see, the option is fine then, thanks!

**Comment by james-stevens** [comment]
np - thanks for the feedback & getting involved.

**Comment by james-stevens** [comment]
Just thought, if you're using MySQL, or more especially MariaDB, as your backend, and you don't already have server side SQL caching enabled, you may see benefits for adding this.

I find it really helps PowerDNS, so I always have it enabled, but it could be just the way I use it.

Of course, it will not make the first zone-list go any faster, so the `Fast Zone List` option is still almost certainly your best bet for solving that issue completely.

I use prometheus/grafana on my servers, so here's the query cache stats. As a lot of my queries are XFR they just don't really get cached, just the general maintenance stuff.

![Selection_2020-05-22_008](https://user-images.githubusercontent.com/30622954/82669215-f6bb7680-9c32-11ea-8c28-bfa6d60c14b5.png)
