### ISSUE TITLE
Cannot add RRs for @

### ISSUE THREAD

**Issue by nwhisper2014** [james-stevens/powerdns-webui#51]
This code does not allow to add RRs for @ (NS, MX, TXT, ...) because the regular expression returns false in hostnameCheck.test(f.rrName.value).

```
        if (f.rrName.value == "") name = ctx.zone;
        else name = `${f.rrName.value}.${ctx.zone}`;

        if (!hostnameCheck.test(f.rrName.value)) {
                errMsg("Invalid host name");
                f.rrName.focus();
                f.rrName.select();
                return false;
                }
```

I was able to get the check to work correctly after editing a regular expression:

FROM
```
const hostnameCheck = /^([a-zA-Z0-9_*]|[a-zA-Z0-9_][a-zA-Z0-9\-_]*[a-zA-Z0-9_])(\.([a-zA-Z0-9_]|[a-zA-Z0-9_][a-zA-Z0-9\-_]*[a-zA-Z0-9_]))*$/
```

TO
```
const hostnameCheck = /^(([a-zA-Z0-9_*]|[a-zA-Z0-9_][a-zA-Z0-9\-_]*[a-zA-Z0-9_])(\.([a-zA-Z0-9_]|[a-zA-Z0-9_][a-zA-Z0-9\-_]*[a-zA-Z0-9_]))*)?$/
```

**Comment by james-stevens** [comment]
I would normally use a blank hostname to add records at the zone apex - that's what this line is referring to
```
if (f.rrName.value == "") name = ctx.zone;
```

but I see doing it that way also fails with this new test !!
The regexp was changed very recently to allow for `*` as a hostname

As `@` isn't really a valid host name, but just a convention for referring to the zone apex, think I will fix the issue in a slightly different way.

```
        if ((f.rrName.value == "")||(f.rrName.value == "@")) name = ctx.zone;
        else {
              name = `${f.rrName.value}.${ctx.zone}`;
              if (!hostnameCheck.test(f.rrName.value)) {
                      errMsg("Invalid host name");
                      f.rrName.focus();
                      f.rrName.select();
                      return false;
                      }
               }

```

But thanks for bringing it to my attention.

**Comment by james-stevens** [comment]
Should be fixed now

**Comment by nwhisper2014** [comment]
It works fine for me now, too. Thank you very much!
