### ISSUE TITLE
It is not possible to change the type of an existing zone

### ISSUE THREAD

**Issue by nwhisper2014** [james-stevens/powerdns-webui#55]
When creating a new zone, you can select its type: Master, Slave, Native. But later it is not possible to change the zone type with powerdns-webui.

It would be great to be able to change the type of existing zones =)

**Comment by james-stevens** [comment]
WOW! I'd have never thought of wanting to do that :)

Thanks for the feedback

**Comment by nwhisper2014** [comment]
In my opinion, this function can at least be useful when a zone is added via import. If you run the command "pdnsutil load-zone ZONE FILE", the zone is imported with the type "native" if this zone has not been previously created. In this case, it would be convenient to change the zone type quickly, without performing a SQL query.

**Comment by james-stevens** [comment]
Yes, I guessed that might be the use - or if you load it up a zone's data by slaving it from another server, then want to switch it to being the master zone (or native), that's quite common.

Looks like `PUT /servers/{server_id}/zones/{zone_id}` can change the zone `kind`
https://doc.powerdns.com/authoritative/http-api/zone.html

**Comment by nwhisper2014** [comment]
I tested the KIND property in Metadata - it works! =)
