### ISSUE TITLE
There is no option in the interface to remove SOA-EDIT from Metadata

### ISSUE THREAD

**Issue by nwhisper2014** [james-stevens/powerdns-webui#56]
If the SOA-EDIT parameter is added to Metadata, it cannot be removed later from the powerdns webui interface because there is no Delete button.

The other parameters in Metadata that I have tested can be deleted.

**Comment by james-stevens** [comment]
Yeah - that's PowerDNS weirdness

Some items the UI shows to you as METADATA items are real METADATA items & some are actually implemented as zone properties.

https://doc.powerdns.com/authoritative/http-api/zone.html#zone

I wished they'd only do one or the other - but it is what it is. To try & make it easier for users I make them all appear as METADATA, but the ones you see listed in the `blockedMeta` object are zone properties faked as METADATA by the UI.

https://github.com/james-stevens/powerdns-webui/blob/master/htdocs/index.html#L285

**Comment by nwhisper2014** [comment]
I tried sending some requests to the API.
First I queried all available Metadata with the command:

`$ curl -s -H 'X-API-Key: secret' http://127.0.0.1:8053/api/v1/servers/localhost/zones/nw.test./metadata | jq '.'`

Got the output:
```
[
  {
    "kind": "ALSO-NOTIFY",
    "metadata": [
      "192.168.11.10",
      "192.168.11.11"
    ],
    "type": "Metadata"
  },
  {
    "kind": "SOA-EDIT",
    "metadata": [
      "INCEPTION-INCREMENT"
    ],
    "type": "Metadata"
  },
  {
    "kind": "SOA-EDIT-API",
    "metadata": [
      "DEFAULT"
    ],
    "type": "Metadata"
  },
  {
    "kind": "TSIG-ALLOW-AXFR",
    "metadata": [
      "transfer."
    ],
    "type": "Metadata"
  },
  {
    "kind": "TSIG-ALLOW-DNSUPDATE",
    "metadata": [
      "zonemanager."
    ],
    "type": "Metadata"
  }
]
```
I then tried removing the SOA-EDIT with the command:

`$curl -s -X DELETE -H 'X-API-Key: secret' http://127.0.0.1:8053/api/v1/servers/localhost/zones/nw.test./metadata/SOA-EDIT`

The result was no error, the SOA-EDIT was successfully removed.
```
[
  {
    "kind": "ALSO-NOTIFY",
    "metadata": [
      "192.168.11.10",
      "192.168.11.11"
    ],
    "type": "Metadata"
  },
  {
    "kind": "SOA-EDIT-API",
    "metadata": [
      "DEFAULT"
    ],
    "type": "Metadata"
  },
  {
    "kind": "TSIG-ALLOW-AXFR",
    "metadata": [
      "transfer."
    ],
    "type": "Metadata"
  },
  {
    "kind": "TSIG-ALLOW-DNSUPDATE",
    "metadata": [
      "zonemanager."
    ],
    "type": "Metadata"
  }
]
```
Maybe I misunderstood you and am wrong somewhere?

**Comment by james-stevens** [comment]
They may have changed things. As you can see from this page in their documentation, `soa_edit` is clearly specified as a `zone property` and it **used** to be that it could ONLY be addressed & modified as a `zone property`

https://doc.powerdns.com/authoritative/http-api/zone.html#zone

As a `zone property` you could only change it by doing a `PUT /servers/{server_id}/zones/{zone_id}`, 

https://doc.powerdns.com/authoritative/http-api/zone.html#put--servers-server_id-zones-zone_id

that's what this code does

https://github.com/james-stevens/powerdns-webui/blob/master/htdocs/index.html#L670

It catches the items that aren't real metadata items & translates them to be a `PUT /servers/{server_id}/zones/{zone_id}`

I did raise a ticket with them to request they should clean up the metadata vs zone-properties thing and move all the zone properties to be real metadata items, so maybe they did that, but I didn't get any notification about it on github. 

== Here's a couple of things to try ==

1. On this line https://github.com/james-stevens/powerdns-webui/blob/master/htdocs/index.html#L287 - try changing `delete: false` to `delete: true`

But it's possible that the entire logic for these faked metadata items can be removed, depending on what version of the server software people are running. Our current stable production platform is Alpine v3.13 which has pdns v4.3.1-r2

2. On line 286, you could try replacing the `const blockedMeta = { ....` declaration with just `const blockedMeta = {};` (empty, no data) and see if that works for you.

What version are you running?

**Comment by nwhisper2014** [comment]
I am using PowerDNS 4.6.2 on Debian 11.

PowerDNS Authoritative Server 4.0 through 4.3, 3.x, and 2.x are End of Life.
https://docs.powerdns.com/recursor/appendices/EOL.html

This is the variant that worked correctly for me:

```
const blockedMeta = {
        //"SOA-EDIT": { name: "soa_edit", list: false, delete: false },
        "SOA-EDIT-API": { name: "soa_edit_api", list: false, delete: true },
        "NSEC3PARAM": { name: "nsec3param", list: false, delete: true },
        "TSIG-ALLOW-AXFR": { name: "master_tsig_key_ids", list: true, delete: true },
        "AXFR-MASTER-TSIG": { name: "slave_tsig_key_ids", list: true, delete: true },
        };
```
        
But I discovered a nuance. With the UI, you can add multiple SOA-EDITs, but only the first one added will work. If you set SOA-EDIT like this:

```
  {
    "kind": "SOA-EDIT",
    "metadata": [
      "INCEPTION-INCREMENT",
      "INCREMENT-WEEKS"
    ],
    "type": "Metadata"
  },
```
  
then the soa_edit parameter will get a value like this:

`"soa_edit": "INCEPTION-INCREMENT",`

If you remove the SOA-EDIT, the soa_edit parameter gets an empty value ("soa_edit": ""). If you assign an empty value to SOA-EDIT, soa_edit will also get an empty value. It seems that removing SOA-EDIT and SOA-EDIT=[""] have the same result.

As far as I understood, SOA-EDIT and soa_edit are two related parameters, but they are not the same thing.

At the same time, with TSIG-ALLOW-AXFR and with the other parameters from the blockedMeta constant, the DELETE method does not work. When I try to delete TSIG-ALLOW-AXFR I get an error:

```
{
  "error": "Unsupported metadata kind 'TSIG-ALLOW-AXFR'"
}
```

**Comment by james-stevens** [comment]
> PowerDNS Authoritative Server 4.0 through 4.3, 3.x, and 2.x are End of Life.

Alpine 3.13 is LTS until 2022-11-01 - https://www.alpinelinux.org/releases/, so they may well be backporting security fixes (like redhat do). It's on my ToDo list to upgrade to a newer release, but life has been forcing other priorities!

> With the UI, you can add multiple SOA-EDITs, but only the first one added will work

So sounds like they've made a good attempt to unify `zone properties` into `metadata` (as I had suggested), but there's some issues to work out - you should probably raise that as a bug.

> At the same time, with TSIG-ALLOW-AXFR and with the other parameters from the blockedMeta constant, the DELETE method does not work.

Works fine for me - again, try commenting it out as you did before.

It *very* odd the error says its *not* a metadata items, cos my code knows this & specifically tries to treat it as a `zone property` - that's why its named in the `const blockedMeta` object.

Like I said, seems to me just removing all of the items in the `blockedMeta` object maybe the best thing to do, as it seems they now do the `metadata` simulation I perform in their API.

- OR - it may be that they have a bug & removing `TSIG-ALLOW-AXFR` now no longer works in the API - maybe you could try a few things with `curl` & see if you can get it to work???

> I agree that PowerDNS has a number of obscure inaccuracies

Probably just a case of not updating their documentation - clearly things have changed in recent releases.

===

To get `ENABLE-LUA-RECORDS` to work, just add it to the `const allMetaItems` list & if it has a restricted set of options it can take, add those into `const metaPickLists`

https://github.com/james-stevens/powerdns-webui/blob/master/htdocs/index.html#L272 (`metaPickLists`)
https://github.com/james-stevens/powerdns-webui/blob/master/htdocs/index.html#L296 (`allMetaItems`)

Its missing from their metadata documentation !! https://doc.powerdns.com/authoritative/domainmetadata.html

So you might want to also raise that as an issue !

> I hope they will not make ambiguous tools and parameters =)

You're so funny - of course they will :laughing: 

> That's a lot of text, I hope the translator "Deepl" didn't let me down and that the meaning is correct :)

100% fine - could have been written by a native ... really !

Thanks for all your input - really helps.

**Comment by nwhisper2014** [comment]
> Works fine for me - again, try commenting it out as you did before.

Yes, it works for you )) Good job! =)

I would only suggest removing the `SOA-EDIT` from the `blockedMeta`. Just like this:

```
--- index.html  2022-06-06 16:20:59.723378115 +0300
+++ index_new.html      2022-06-06 16:20:30.637543960 +0300
@@ -286,7 +286,6 @@

 // these appear as metadata items but are handled as zone properties - lol
 const blockedMeta = {
-       "SOA-EDIT": { name: "soa_edit", list: false, delete: false },
        "SOA-EDIT-API": { name: "soa_edit_api", list: false, delete: true },
        "NSEC3PARAM": { name: "nsec3param", list: false, delete: true },
        "TSIG-ALLOW-AXFR": { name: "master_tsig_key_ids", list: true, delete: true },
```

But this might not work for pdns 4.3.x and you will have to add a version checker. Of course, it's up to you to make that change or leave it as it is for now =)

About `ENABLE-LUA-RECORDS`, the documentation says: "To enable this feature, either set 'enable-lua-records' in the configuration, or set the 'ENABLE-LUA-RECORDS' per-zone metadata item to 1." (https://doc.powerdns.com/authoritative/lua-records/index.html).

However...

> Its missing from their metadata documentation !! ...

... yes, `ENABLE-LUA-RECORDS` is not in the Metadata list and is not added by either an API call or the pdnsutil utility. I think that `ENABLE-LUA-RECORDS` at the moment, like autoslave (superslave/supermaster), is only activated by direct insertion into the database, so this parameter did not work after being added to `metaPickLists`/`allMetaItems`. 

PowerDNS is very interesting, but not completely unambiguous =))

Thank you! I really like your PowerDNS WebUI.

**Comment by james-stevens** [comment]
> you will have to add a version checker

yes - I think like that might be necessary for a while - I will upgrade my systems soon, but there will be others who do not, possibly RedHat - if they don't update then there will be lots who will not. 

> yes, `ENABLE-LUA-RECORDS` is not in the Metadata list and is not added by either an API call or the pdnsutil utility

So no hurry to add it yet ... :rofl: 

> PowerDNS is very interesting, but not completely unambiguous =))

like all software, it has its faults, but I think it is the easiest DNS Master to use by quite a long way

> I really like your PowerDNS WebUI

thanks, me too - I use it pretty much every day - I find being able to see the data makes such a difference

But I would like to make it look a little more modern, "dark" seems in fashion & I prefer dark as its easier on the eyes. Something like this.... https://www.shakedex.com/a/xn--5p9h - or gituhb/dark or twitter/dark

What do you think?

Send me a URL if there's a UI you like that you think could be good inspiration

**Comment by nwhisper2014** [comment]
I like the look of the interfaces 
- netbox - https://github.com/netbox-community/netbox
- gitea - https://github.com/go-gitea/gitea
- google cloud console
- github
- gitlab

I prefer the light theme, but the dark theme is also a good choice )

**Comment by james-stevens** [comment]
> I prefer the light theme, but the dark theme is also a good choice )

then obviously it needs both a "light" & "dark" option :wink:

**Comment by nwhisper2014** [comment]
This is similar to what GitHub Releases do =)

**Comment by james-stevens** [comment]
Yeah - that's a good idea - I'll create a github `Release` as well

**Comment by james-stevens** [comment]
> At the same time, with TSIG-ALLOW-AXFR and with the other parameters from the blockedMeta constant, the DELETE method does not work. When I try to delete TSIG-ALLOW-AXFR I get an error:

I just tried deleting a `TSIG-ALLOW-AXFR` & it worked fine for me with P/DNS Server v4.6.2 on Alpine v3.16

**Comment by james-stevens** [comment]
"SOA-EDIT": { name: "soa_edit", list: false, delete: true },

If I just change `delete: false` to `delete: true` then the `Delete` button appears & sort-of works. It set `SOA-EDIT` to blank instead of actually deleting it. It seems to delete `SOA-EDIT-API` in the same way.

The CRAZY thing is *NONE* of them are actually "zone properties", there's no such thing in the database - in the database they are *ALL* metadata - except `KIND` which really is a zone property (&, of course, the zone's name!!).

Looks like you can now address `SOA-EDIT` as if it was a real metadata item, but all the others still have to be addressed as zone properties. - why, oh why !?!?!

As you pointed out, the disadvantage of addressing `SOA-EDIT` as a real metadata item is that pdns allows it to have multiple values, which it really shouldn't.

**Comment by james-stevens** [comment]
https://github.com/PowerDNS/pdns/issues/11697

**Comment by nwhisper2014** [comment]
Yes, in the dev version of index.html the SOA-EDIT property can now be removed. Every patch makes the UI better, that's great =)

**Comment by james-stevens** [comment]
Couldn't do it without this kind of great feedback !!

**Comment by james-stevens** [comment]
I'll merge `dev` to `master`

**Comment by nwhisper2014** [comment]
> I've raised an issue with PowerDNS to try & cover everything you found, please add more information, if you wish

I read the text of the bug report: I have nothing to add =) I hope that pdns authors will make Metadata and zone properties more understandable =)

**Comment by james-stevens** [comment]
> I read the text of the bug report: I have nothing to add =) I hope that pdns authors will make Metadata and zone properties more understandable =)

Don't hold your breath - I've been moaning to them about this for years !!

Literally, years !!

Why they insist on faking that some items are `zone properties` when they are really `metadata` I just don't know - the only thing I can think of is that with some database back-ends those particular items *really* are `zone properties` and not really `metadata`.

It would be a weak excuse, but possible.
